[package]
name = "turbine_rs_prereq"
version = "0.1.0"
edition = "2021"

[features]
idl-build = ["anchor-lang/idl-build"]

[dependencies]
bs58 = "0.5.1"
borsh = "1.5.1"
solana-client = "~1.17.3"
solana-program = "~1.17.3"
solana-sdk = "~1.17.3"
anchor-lang = "~0.30.1"
anchor-client = "~0.30.1"
